name: build-and-deploy
run-name: Deploy to Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install and Build
        run: |
          yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: dist
          branch: gh-pages
