name: Cron CI

on:
  schedule:
    - cron: "30 15 15 11 5"
    # - cron: "30 0 1 * *" # runs on the first day of each month at 0:30 am

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 20
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  deploy-to-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          ref: netlify
      - name: Install & Build
        run: |
          yarn
          yarn build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
